Moving to Ruff and `pyproject.toml`
nestauk/ds-cookiecutter pull request #204
Opened 2024-12-19 20:52 UTC by HarrisonWilde

Not quite passing all tests but have switched fully to ruff and as a result ditched most of the other config files.

I cannot for the life of me get all tests to pass, because of weird issues in the makefile I have begun to address (This also fixes #203), one of which is the bug in the `conda-remove` step but now I cannot get the pre-commit hooks and install to work at the same time, seems to be some issue with conda on my system.

Main things to discuss before full PR are:
1. Resolving the issues w the tests (and we may want to add more at some point but for now these seem to work ok)
2. How precisely we want to use Ruff, you can see that I have pretty much kept in line with the old ways with a few changes like standard line length (88 from 80) and fewer ignores + standard `isort`, etc.

---

Checklist:

- [ ] Updated documentation
- [ ] CI passes
- [ ] Labelled PR major/minor/patch

2024-12-19 21:27 UTC, HarrisonWilde commented
Checks now pass here, but still not on my machine, would be good to figure this out as my setup is fairly standard iiuc.

2024-12-20 11:06 UTC, caldwellst requested changes
Okay, just a few comments for the moment. I need to install conda and then will run the tests and test out spinning up a project using the cookiecutter.

2024-12-20 11:06 UTC, caldwellst commented on docs/docs/structure.md
> +├── outputs/                         |  OUTPUTS PRODUCED FROM THE PROJECT
Not something to solve now, but have not seen in a long time outputs stored on GitHub. I think it increases risk of accidentally sharing information that can't go public or interim results that have yet to be validated. Previous workplaces had a set of utilities that allowed us to easily save data outputs to the blob or visual outputs to our shared drive.

What do you think? Maybe another issue to open?

2024-12-20 11:06 UTC, caldwellst commented on tests/test_creation.py
>          if pytest.param.get("openess") == "private":
This isn't actually defined in `conftest.py` so this just always is `None` I think. It's also `openness` in the cookiecutter config. Seems an existing error in the testing we should fix.

2024-12-20 11:06 UTC, caldwellst commented on .pre-commit-config.yaml
> -      # - id: flake8
Move to `ruff` here as well? Seems strange to still have `black` here but not in the projects.

2024-12-20 11:43 UTC, HarrisonWilde commented on .pre-commit-config.yaml
> -      # - id: flake8
I have a separate PR for hooks, it was already getting pretty inflated, I could make it consistent though yeah.

2024-12-20 11:43 UTC, HarrisonWilde commented on tests/test_creation.py
>          if pytest.param.get("openess") == "private":
Ah interesting, let me look further into this

2024-12-20 11:45 UTC, HarrisonWilde commented on docs/docs/structure.md
> +├── outputs/                         |  OUTPUTS PRODUCED FROM THE PROJECT
I think it's more just for file tree structure, if you look in the `.gitignore` they exclude sensibly the contents of inputs and outputs, might be more convo to have over that but I think its ok.

2024-12-20 11:52 UTC, HarrisonWilde commented on .pre-commit-config.yaml
> -      # - id: flake8
Ok I have done a minimal change

2024-12-20 13:58 UTC, caldwellst commented
I am unable to locally pass `test_precommit()`. Everything else is successful. Potentially something with my conda setup, but haven't used it in at least 5 years, so not particularly sure how to troubleshoot.

```
../../../miniconda3/lib/python3.10/subprocess.py:526: CalledProcessError
--------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------
Installing and configuring git pre-commit hooks/bin/bash: /Users/seth.caldwell/miniconda3/envs/nestatestcookie/bin/pre-commit: /Users/seth.caldwell/miniconda3/envs/nestatestcookie/bin/python3.10: bad interpreter: No such file or directory
Git pre-commit setup failed, check .cookiecutter/state/setup-git.log for more info
```

@HarrisonWilde Have you been able to get all checks passing locally?

2024-12-20 15:05 UTC, caldwellst approved these changes
Overall, everything looks good. I can't resolve the tests, but also can't resolve the tests in the base `master` branch, so not too concerned there. Will need to be a wider look at tests at some point in the future.

To me, the settings you've put in place for `ruff` make sense, but probably those who have worked on previous projects will have more concrete input, particularly on docstring styling or particular approaches we use here.

2024-12-20 15:05 UTC, caldwellst commented on {{ cookiecutter.repo_name }}/pyproject.toml
> +select = ["ANN", "B", "C", "D", "E", "F", "I", "N", "W"]
Looks like a reasonable selection! Will be mainly interested how people using the current code base feel. Particularly around mandating a docstring convention? But I am all for it!

2024-12-20 15:05 UTC, caldwellst commented on {{ cookiecutter.repo_name }}/pyproject.toml
> +mccabe = { max-complexity = 10 }
Yes please!

2024-12-23 10:08 UTC, HarrisonWilde commented on {{ cookiecutter.repo_name }}/pyproject.toml
> +select = ["ANN", "B", "C", "D", "E", "F", "I", "N", "W"]
Yeah, I noticed that was enabled in current flake8 config, I don't usually support those but just tried to stay close for now

2025-01-27 12:15 UTC, closed without merging